// Re-exports explícitos (vite/rollup no infiere named exports a través de
// `export *` cuando shared se compila a CJS). Agrupados por dominio: al añadir un
// schema, exporta aquí el schema Y su tipo.

export {
  CRM_AREAS,
  TEAM_ROLES,
  TEAM_ROLE_LABELS,
  ROLE_AREAS,
  roleCanAccess,
  STAGE_KINDS,
  STAGE_KIND_LABELS,
  isClosedKind,
  STAGE_COLORS,
  CRM_CURRENCY,
  CRM_LOCALE,
  LEAD_SERVICES,
  LEAD_SECTORS,
  LEAD_SOURCES,
  DATA_SOURCES,
  DATA_SOURCE_LABELS,
  sourceLabel,
  normalizeSource,
  KNOWN_CITIES,
  normalizeCity,
  formatPersonName,
  isAllCaps,
  CARGO_GROUPS,
  CARGO_FAMILIES,
  cargoGroup,
  PUBLIC_EMAIL_DOMAINS,
  isPublicEmailDomain,
  emailDomain,
  corporateDomainFromEmail,
  normalizeDomain,
} from './enums';
export type { CrmArea, TeamRole, StageKind, StageColor } from './enums';

export { computeLeadHealth } from './health';
export type { HealthBand, LeadHealth } from './health';

export { MENTION_TOKEN_RE, extractMentionIds } from './mentions';

export {
  ContactStatusSchema,
  PhoneE164Schema,
  StageKindSchema,
  StageColorSchema,
  PipelineStageSchema,
  CreatePipelineStageSchema,
  UpdatePipelineStageSchema,
  ReorderStagesSchema,
  StageListResponseSchema,
  LeadPersonRefSchema,
  LeadHealthBandSchema,
  LeadSchema,
  CreateLeadSchema,
  UpdateLeadSchema,
  LOST_REASONS,
  canonicalLostReason,
  MoveLeadSchema,
  LeadListResponseSchema,
  FunnelStageSchema,
  LossRowSchema,
  SlaBreachSchema,
  PipelineAnalyticsSchema,
  StageStaySchema,
  LeadStageHistorySchema,
  OwnerPerformanceSchema,
  PipelinePerformanceSchema,
  SignalLeadSchema,
  OverdueTaskSchema,
  IcpRowSchema,
  CrmInsightsSchema,
  CrmGoalSchema,
  CompanySchema,
  CreateCompanySchema,
  UpdateCompanySchema,
  CompanyListResponseSchema,
  CompanyFacetsSchema,
  PersonRefSchema,
  CompanyDetailSchema,
  PersonSchema,
  CreatePersonSchema,
  UpdatePersonSchema,
  PersonListResponseSchema,
  PeopleFacetsSchema,
  PersonDetailSchema,
  ImportPeopleResultSchema,
} from './schemas/crm.schema';
export type {
  ContactStatus,
  PipelineStage,
  CreatePipelineStageInput,
  UpdatePipelineStageInput,
  ReorderStagesInput,
  StageListResponse,
  LeadPersonRef,
  Lead,
  LeadHealthBand,
  CreateLeadInput,
  UpdateLeadInput,
  MoveLeadInput,
  LeadListResponse,
  FunnelStage,
  LossRow,
  SlaBreach,
  PipelineAnalytics,
  StageStay,
  LeadStageHistory,
  OwnerPerformance,
  PipelinePerformance,
  SignalLead,
  OverdueTask,
  IcpRow,
  CrmInsights,
  CrmGoal,
  Company,
  CreateCompanyInput,
  UpdateCompanyInput,
  CompanyListResponse,
  Facet,
  CompanyFacets,
  PersonRef,
  CompanyDetail,
  Person,
  CreatePersonInput,
  UpdatePersonInput,
  PersonListResponse,
  PeopleFacets,
  PersonDetail,
  ImportPeopleResult,
} from './schemas/crm.schema';

export {
  CrmEntityType,
  CrmNoteKind,
  TOUCHPOINT_KINDS,
  CrmNoteSchema,
  CreateCrmNoteSchema,
  UpdateCrmNoteSchema,
  NoteListResponseSchema,
  CrmTaskSchema,
  CreateCrmTaskSchema,
  UpdateCrmTaskSchema,
  TaskListResponseSchema,
  PendingCrmTaskSchema,
  PendingTasksResponseSchema,
} from './schemas/comments.schema';
export type {
  CrmEntityTypeValue,
  CrmNoteKindType,
  CrmNote,
  CreateCrmNoteInput,
  UpdateCrmNoteInput,
  NoteListResponse,
  CrmTask,
  CreateCrmTaskInput,
  UpdateCrmTaskInput,
  TaskListResponse,
  PendingCrmTask,
  PendingTasksResponse,
} from './schemas/comments.schema';

export { ViewPrefConfigSchema, ViewPrefSchema, SaveViewPrefSchema } from './schemas/view-pref.schema';
export type { ViewPrefConfig, ViewPref, SaveViewPrefInput } from './schemas/view-pref.schema';

export {
  TeamRoleSchema,
  TeamMemberSchema,
  TeamMemberListResponseSchema,
  TeamMeSchema,
  UpdateTeamMemberSchema,
} from './schemas/team.schema';
export type {
  TeamMember,
  TeamMemberListResponse,
  TeamMe,
  UpdateTeamMemberInput,
} from './schemas/team.schema';
